language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  api_key:
    secure: ClbWH6HUB56hPuh2kB4XpqQLsleyZu3lZp2Edq4zKXhy4AzpU+2MRMo4jQyDHLgQXX4l3bOjKZrvaLppL7HM5gqZty3Be1kJFhBkP6kI7ABcP4A7rw7gHJ8kr7MehYARVK/Ahxr53QP1Ug2pIzCqDCa5oQHLrrNlYgH1UIVvnRYjbFux1GPAp0q9BaiMyZCc4lpXDKfuS16CeibnbrCvOvSs00APbYlDYdueNx9G810oiazvBOWSAu3JBiEQt6tSgMQHpG+BgdB7AFDrhdBDVyCkxKsA2oc8XiHEq4fCourZCO4/cypaEm/kDbtYO0hYgx6aEvPIf/i1LpAYBdnLduIK2pgAbs1axfVL5yhzo2+Fq8DqjAmN//1kA33wfpTlYxaaKlyOXBCVMd6XhunJHqVScd5sPw242kvxG2tKOCNMvWAit9AgXjdS45SQMDua0LL7Wq9SQD4/qp9tA76Pp8hpJtLHRXeXPsm3CFAnsPgQztXz6EupaVab3Qn2dYYdUk/GDOsRfgzx3FRkIt7Sl62nB79av4PO3IyOkLkO63ZFf09LHaVcSpWwK1BMvfv9OnI/uVWo1cxLhYeuWHhIUNQ1WxvpjgkI9DJja7zvSDX7CrjbRS1i9kmRmG7JS6DaiVgwmsz1sr2FF0wvHJYHhf65wP+PioN9fcJo6SvQ8Zo=
  app: beam-hub-backend
  on:
    repo: janbro/BeamHubBackend
    branch: master
