language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  api_key:
    secure: CP8KRvF9HV5+sG0bijyMhtph//cFallDKxp+qGnn7nlbTXuf2LGSfO9L0quJCty3PVcWTfWH5aIQCS9XCu+sxfUjD/BbfmpVc9WBzQGcnEsvhFp5h9DuFkAQbsR+5LcWgmWuPZ62OfYjMWzut3liHMQMUkQoT3LOvf2+pdZvkVvob/86VPb2mCPseP7k/SAD1JeEZv5Nrrke8uHb/W0VZtGEoVl2RJeXIFCCBu+eVP/tUHke6KY+C9TUPODIul3zjQZunY+gt4QDteYQC/RFfRlZAdi0NzjvlPMycb+40ScEBI5tzmPMOve4kEKQ6q0Hch7L4gmVh6akVBtk5DK5wnOY2fsS3uA/BLm/BU6et/5tSw8TpJVhvCCfto1khWHxQvg7vOqBo45J8nCNuAKFfUjtfN9jTJnYWCRNdej5bEDIED/fRBVh1qGtAjcl3Yzf2MmS85TfCPTm+5Oam0qBTlsGv9vkJFLGvMzP+/f1cMRvYYhG7HxMwoYLKneNbCC/eYXaRMH4Cb1NxsYoEutfpI6kd073NlxHiUtFd2NfGl/uHcYzJBO2UiYClOpLbfwM1yNZ1X8Y8N6wuh8zZe+Fr/wpoXkxh12zTWSfGfwZphZByaaDzLsko0zyMcHGYya/MCc7M2xEkO+pcpEYwCLOHPCwKo7uxkp1y3yng9uzNus=
  app: pibeac
  on:
    repo: janbro/pibeac
    branch: master
before_install:
- npm run build
after_success:
- npm run compodoc && bash ./deploy.sh